### ISSUE TITLE
作者？看一下

### ISSUE THREAD

**Issue by wd550777** [luxianyou/fcoin#3]
为啥还需要授权 不是破解版吗

**Comment by wd550777** [comment]
我的QQ 550777495

**Comment by luxianyou** [comment]
The second is authorization. Forgot to put the decryption key. To compensate you, the second one comes from another set of trading robots.

**Comment by wd550777** [comment]
那我现在应该如何操作？ 第二个下载不了啊 还得付款
另外这两个哪个执行效率更高一点兄弟

**Comment by wd550777** [comment]
Which is better the first or the second?

Is this the first one that's not working?
If that's the case, how am I supposed to download the second one?
Do I need to buy again?

**Comment by luxianyou** [comment]
You can look at the pictures I sent, and the second one can set a low buy-to-sell ratio.

**Comment by wd550777** [comment]
how am I supposed to download the second one?
Do I need to buy again?

The second I have a free version,
Is your premium version of crack？

**Comment by wd550777** [comment]
The first I bought, but can't use
As compensation, the second directly send me email
550777495 @qq.com

**Comment by luxianyou** [comment]
The second version will not be sent to you. If you need it, you can buy it. I will refund you the first money.
Please provide a btc address

**Comment by wd550777** [comment]
BTC:  1Q5Qz4vLf9PzXHrfhiFB3GTS9JTSBWWs7r

**Comment by luxianyou** [comment]
我只能给你0.003个BTC,因为box扣了我0.001个，不好意思

**Comment by luxianyou** [comment]
I can only give you 0.003 BTC, because the box deducted me 0.001, I am sorry

**Comment by wd550777** [comment]
OK
